### ISSUE TITLE
Not work with Redmine 4.0.2

### ISSUE THREAD

**Issue by ZerooCool** [altsol/redmine_mattermost#33]
**I use Debian Stretch 9 Stable with RVM**
https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian_avec_RVM

If i add this plugin and restart apache, i can't show the redmine page.
We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

**Then, i test bundle exec rake redmine:plugins:migrate but rake is aborted**

```
~/redmine-4.0-stable/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/redmine/redmine-4.0-stable)
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/opt/redmine/redmine-4.0-stable/plugins/redmine_rocketchat-master/init.rb:28:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:175:in `block in load'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `each'
/opt/redmine/redmine-4.0-stable/lib/redmine/plugin.rb:166:in `load'
/opt/redmine/redmine-4.0-stable/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0-stable/config/environment.rb:14:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.4.5@redmine-4.0-stable/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by Yumash** [comment]
+1

**Comment by pcdog** [comment]
still seems to be an issue :)

**Comment by scottcc** [comment]
yep, broken solid.

**Comment by thanosk** [comment]
Please try v0.6 and report back if it doesnot solve the issue
